spec_spaces <- tspec_df(
    tib_chr("id"),
    tib_chr("name"),
    tib_chr("color"),
    tib_lgl("private"),
    tib_chr("avatar"),
    tib_lgl("admin_can_manage"),
    tib_df(
        "statuses",
        tib_chr("id"),
        tib_chr("status"),
        tib_chr("type"),
        tib_dbl("orderindex"),
        tib_chr("color"),
    ),
    tib_lgl("multiple_assignees"),
    tib_df(
        "features",
        .names_to = ".names",
        tib_lgl("enabled", required = FALSE),
        tib_lgl("start_date", required = FALSE),
        tib_lgl("remap_due_dates", required = FALSE),
        tib_lgl("remap_closed_due_date", required = FALSE),
        tib_lgl("harvest", required = FALSE),
        tib_lgl("rollup", required = FALSE),
        tib_int("default_to_billable", required = FALSE),
        tib_df(
            "priorities",
            .required = FALSE,
            tib_chr("color"),
            tib_chr("id"),
            tib_dbl("orderindex", transform = as.numeric, ptype_inner = character()),
            tib_chr("priority"),
        ),
        tib_lgl("per_assignee", required = FALSE),
        tib_lgl("subtasks", required = FALSE),
        # tib_unspecified("checklists", required = FALSE),
        # tib_unspecified("comments", required = FALSE),
    ),
    tib_lgl("archived"),
    tib_df(
        "members",
        .required = FALSE,
        tib_row(
            "user",
            tib_chr("id", transform = as.character, ptype_inner = integer()),
            tib_chr("username"),
            tib_chr("color"),
            tib_chr("profilePicture"),
            tib_chr("initials"),
        ),
    ),
)
