spec_tasks <- tspec_df(
    tib_chr("id"),
    # tib_unspecified("custom_id"),
    tib_chr("name"),
    tib_chr("text_content"),
    tib_chr("description"),
    tib_row(
        "status",
        tib_chr("status"),
        tib_chr("color"),
        tib_chr("type"),
        tib_int("orderindex"),
    ),
    tib_int("orderindex", transform = as.integer, ptype_inner = character()),
    tib_custom("date_created", cu_date_from),
    tib_custom("date_updated", cu_date_from),
    tib_custom("date_closed", cu_date_from),
    tib_chr("date_done"),
    tib_lgl("archived"),
    tib_row(
        "creator",
        tib_chr("id", transform = as.character, ptype_inner = integer()),
        tib_chr("username"),
        tib_chr("color"),
        tib_chr("email"),
        tib_chr("profilePicture"),
    ),
    tib_df(
        "assignees",
        tib_chr("id", transform = as.character, ptype_inner = integer()),
        tib_chr("username"),
        tib_chr("color"),
        tib_chr("initials"),
        tib_chr("email"),
        tib_chr("profilePicture"),
    ),
    # tib_unspecified("watchers"),
    tib_df(
        "checklists",
        tib_chr("id"),
        tib_chr("task_id"),
        tib_chr("name"),
        tib_custom("date_created", cu_date_from),
        tib_int("orderindex"),
        tib_int("creator"),
        tib_int("resolved"),
        tib_int("unresolved"),
        tib_df(
            "items",
            tib_chr("id"),
            tib_chr("name"),
            tib_dbl("orderindex"),
            tib_row(
                "assignee",
                tib_int("id", required = FALSE),
                tib_chr("username", required = FALSE),
                tib_chr("email", required = FALSE),
                tib_chr("color", required = FALSE),
                tib_chr("initials", required = FALSE),
                tib_chr("profilePicture", required = FALSE),
            ),
            # tib_unspecified("group_assignee"),
            tib_lgl("resolved"),
            # tib_unspecified("parent"),
            tib_custom("date_created", cu_date_from),
            # tib_unspecified("children"),
        ),
    ),
    tib_df(
        "tags",
        tib_chr("name"),
        tib_chr("tag_fg"),
        tib_chr("tag_bg"),
        tib_int("creator"),
    ),
    tib_chr("parent"),
    tib_row(
        "priority",
        tib_chr("color", required = FALSE),
        tib_chr("id", required = FALSE),
        tib_chr("orderindex", required = FALSE),
        tib_chr("priority", required = FALSE),
    ),
    tib_custom("due_date", cu_date_from),
    tib_custom("start_date", cu_date_from),
    tib_int("points"),
    tib_int("time_estimate"),
    tib_int("time_spent", required = FALSE),
    tib_df(
        "custom_fields",
        tib_chr("id"),
        tib_chr("name"),
        tib_chr("type"),
        tib_row(
            "type_config",
            tib_int("default", required = FALSE),
            # tib_unspecified("placeholder", required = FALSE),
            tib_df(
                "options",
                .required = FALSE,
                tib_chr("id"),
                tib_chr("name", required = FALSE),
                tib_chr("color"),
                tib_int("orderindex", required = FALSE),
                tib_chr("label", required = FALSE),
            ),
            tib_lgl("simple", required = FALSE),
            tib_chr("formula", required = FALSE),
            tib_chr("version", required = FALSE),
            tib_lgl("is_dynamic", required = FALSE),
            tib_variant("return_types", required = FALSE),
            tib_chr("calculation_state", required = FALSE),
            tib_lgl("new_drop_down", required = FALSE),
            tib_lgl("single_user", required = FALSE),
            # tib_unspecified("include_groups", required = FALSE),
            tib_lgl("include_guests", required = FALSE),
            tib_lgl("include_team_members", required = FALSE),
            tib_int("precision", required = FALSE),
            tib_chr("currency_type", required = FALSE),
            tib_int("end", required = FALSE),
            tib_int("start", required = FALSE),
            tib_int("count", required = FALSE),
            tib_chr("code_point", required = FALSE),
            tib_row(
                "tracking",
                .required = FALSE,
                tib_lgl("subtasks", required = FALSE),
                tib_lgl("checklists", required = FALSE),
                tib_lgl("assigned_comments", required = FALSE),
            ),
            tib_int("complete_on", required = FALSE),
            # tib_unspecified("fields", required = FALSE),
            tib_chr("subcategory_id", required = FALSE),
            tib_lgl("linked_subcategory_access", required = FALSE),
            tib_chr("subcategory_inverted_name", required = FALSE),
            tib_dbl("reset_at", required = FALSE),
        ),
        tib_custom("date_created", cu_date_from),
        tib_lgl("hide_from_guests"),
        tib_lgl("required"),
        tib_variant("value", required = FALSE),
    ),
    tib_df(
        "dependencies",
        tib_chr("task_id"),
        tib_chr("depends_on"),
        tib_int("type"),
        tib_custom("date_created", cu_date_from),
        tib_chr("userid"),
        tib_chr("workspace_id"),
    ),
    tib_df(
        "linked_tasks",
        tib_chr("task_id"),
        tib_chr("link_id"),
        tib_custom("date_created", cu_date_from),
        tib_chr("userid"),
        tib_chr("workspace_id"),
    ),
    tib_chr("team_id"),
    tib_chr("url"),
    tib_row(
        "sharing",
        tib_lgl("public"),
        # tib_unspecified("public_share_expires_on"),
        tib_variant("public_fields"),
        tib_chr("token"),
        tib_lgl("seo_optimized"),
        tib_int("permission_level", required = FALSE),
        tib_row(
            "permissions",
            .required = FALSE,
            tib_lgl("can_comment", required = FALSE),
            tib_chr("name", required = FALSE),
        ),
    ),
    tib_chr("permission_level"),
    tib_row(
        "list",
        tib_chr("id"),
        tib_chr("name"),
        tib_lgl("access"),
    ),
    tib_row(
        "project",
        tib_chr("id"),
        tib_chr("name"),
        tib_lgl("hidden"),
        tib_lgl("access"),
    ),
    tib_row(
        "folder",
        tib_chr("id"),
        tib_chr("name"),
        tib_lgl("hidden"),
        tib_lgl("access"),
    ),
    tib_row(
        "space",
        tib_chr("id"),
    ),
)
