spec_teams <- tspec_df(
    tib_chr("id"),
    tib_chr("name"),
    tib_chr("color"),
    tib_chr("avatar"),
    tib_df(
        "members",
        tib_row(
            "user",
            tib_chr("id", transform = as.character),
            tib_chr("username"),
            tib_chr("email"),
            tib_chr("color"),
            tib_chr("profilePicture"),
            tib_chr("initials"),
            tib_int("role"),
            # tib_unspecified("custom_role"),
            tib_custom("last_active", cu_date_from),
            tib_custom("date_joined", cu_date_from),
            tib_custom("date_invited", cu_date_from),
        ),
        tib_row(
            "invited_by",
            .required = FALSE,
            tib_int("id", required = FALSE),
            tib_chr("username", required = FALSE),
            tib_chr("color", required = FALSE),
            tib_chr("email", required = FALSE),
            tib_chr("initials", required = FALSE),
            tib_chr("profilePicture", required = FALSE),
        ),
        tib_lgl("can_see_time_spent", required = FALSE),
        tib_lgl("can_see_time_estimated", required = FALSE),
        tib_lgl("can_see_points_estimated", required = FALSE),
        tib_lgl("can_edit_tags", required = FALSE),
        tib_lgl("can_create_views", required = FALSE),
    ),
)
