spec_lists <- tspec_df(
    tib_chr("id"),
    tib_chr("name"),
    tib_int("orderindex"),
    tib_chr("content", required = FALSE),
    tib_row(
        "status",
        tib_chr("status", required = FALSE),
        tib_chr("color", required = FALSE),
    ),
    # tib_unspecified("priority"),
    tib_row(
        "assignee",
        tib_chr("color", required = FALSE),
        tib_chr("username", required = FALSE),
        tib_chr("initials", required = FALSE),
        tib_chr("profilePicture", required = FALSE),
    ),
    tib_int("task_count"),
    tib_custom("due_date", cu_date_from),
    tib_custom("start_date", cu_date_from),
    tib_row(
        "folder",
        tib_chr("id"),
        tib_chr("name"),
        tib_lgl("hidden"),
        tib_lgl("access"),
    ),
    tib_row(
        "space",
        tib_chr("id"),
        tib_chr("name"),
        tib_lgl("access"),
    ),
    tib_lgl("archived"),
    tib_lgl("override_statuses"),
    tib_chr("permission_level"),
)
